Repository dev-zipida-com/ojt, pull requests merged in 2020-07, with the labels that each got.

#5 Ojt/yj.kang
  .DS_Store
  yj.kang/.DS_Store
  yj.kang/0702_gitStudy.md
Labels: documentation

#6 learn to github and console
  jw.jeong/example.md
Labels: documentation

#7 Make Linux Study .md File
  yj.kang/0703_linuxStudy.md
Labels: documentation

#10 Ojt/linux study
  jw.jeong/linuxAndSSH/linuxAndSSH.md
Labels: documentation

#11 Ojt/web basic
  yj.kang/0703_ECMAScript.md
  yj.kang/0703_Javascript.md
  yj.kang/0703_Nodejs.md
  yj.kang/0703_webBasic.md
  yj.kang/0704_Babel.md
Labels: documentation

#15 CREATE TODOLIST
  yj.kang/work1-1/app.js
  yj.kang/work1-1/index.html
  yj.kang/work1-1/style.css
Labels: enhancement

#14 Add todo list code
  jw.jeong/work1-1/app.js
  jw.jeong/work1-1/style.css
Labels: enhancement

#16 Fix todo error
  jw.jeong/work1-1/app.js
Labels: bug

#17 FIX APP.JS
  yj.kang/work1-1/app.js
Labels: bug

#19 Add to fetchapi code
  jw.jeong/work1-2/Asynchrony.md
  jw.jeong/work1-2/app.js
  jw.jeong/work1-2/index.html
  jw.jeong/work1-2/promise/promise.html
  jw.jeong/work1-2/promise/promise.js
  jw.jeong/work1-2/style.css
Labels: enhancement

#20 ADD FETCH API
  yj.kang/work1-2/app.js
  yj.kang/work1-2/index.html
  yj.kang/work1-2/study.md
  yj.kang/work1-2/style.css
Labels: enhancement

#23 Add work1-3
  jw.jeong/work1-3/app.js
  jw.jeong/work1-3/index.html
  jw.jeong/work1-3/style.css
Labels: enhancement

#24 Add work1-3
  yj.kang/work1-3/app.js
  yj.kang/work1-3/index.css
  yj.kang/work1-3/index.html
Labels: enhancement
